---
title: "Sexual identity and mental health outcomes among adolescents and young adults in Stockholm County, SPHC-B 2010"
author: Willi Zhang
email: willi.zhang@ki.se
output: html_notebook
editor_options: 
  chunk_output_type: console
---

### 1. Load Packages
```{r}
library(haven)
library(tidyverse)
library(finalfit)
library(lubridate)
library(naniar)
library(jomo)
library(mitml)
library(mitools)
library(survey)
library(svyVGAM)
library(vcd)
library(rcompanion)
source('helper_functions.R') # helper function
```

### 2. Import and Prepare Data
```{r}
# load('/Volumes/projects/LGBT Project data/d_2010.RData')
# d_2010_old <- d_2010
# rm( d_2010 )
d_2010 <- read_sas('/Volumes/projects/LGBT Project data/sphc10_14_21_updated.sas7bdat')
summary( d_2010$lopnr )
# length( intersect( d_2010_old$lopnr, d_2010$lopnr ) ) == nrow( d_2010 ) # TRUE
# identical( d_2010_old$lopnr, d_2010$lopnr ) # TRUE
# rm( d_2010_old )

# check duplicate data
# id_duplicate <- readxl::read_xlsx('/Volumes/projects/LGBT Project data/Duplicates_2010.xlsx')
# d_2010 %>% filter( lopnr %in% id_duplicate$LopNr ) %>% View()

# sampling strata
n_miss( d_2010$stratum )
d_2010$sampling_strata <- as.factor( d_2010$stratum )
length( unique( d_2010$sampling_strata ) ) # 39 strata

d_2010 <- d_2010 %>%
  mutate( sampling_strata_region = recode( sampling_strata, 
                                           `2101` = "Upplands-Väsby",
                                           `2102` = "Vallentuna",
                                           `2103` = "Österåker",
                                           `2104` = "Värmdö",
                                           `2105` = "Järfälla",
                                           `2106` = "Ekerö",
                                           `2107` = "Huddinge",
                                           `2108` = "Botkyrka",
                                           `2109` = "Salem",
                                           `2110` = "Haninge",
                                           `2111` = "Tyresö",
                                           `2112` = "Upplands-Bro",
                                           `2113` = "Nykvarn",
                                           `2114` = "Täby",
                                           `2115` = "Danderyd",
                                           `2116` = "Sollentuna",
                                           `2117` = "Södertälje",
                                           `2118` = "Nacka",
                                           `2119` = "Sundbyberg",
                                           `2120` = "Solna",
                                           `2121` = "Lidingö",
                                           `2122` = "Vaxholm",
                                           `2123` = "Norrtälje",
                                           `2124` = "Sigtuna",
                                           `2125` = "Nynäshamn",
                                           `2201` = "Rinkeby-Kista",
                                           `2202` = "Spånga-Tensta",
                                           `2203` = "Hässelby-Vällingby",
                                           `2204` = "Bromma",
                                           `2205` = "Kungsholmen",
                                           `2206` = "Norrmalm",
                                           `2207` = "Östermalm",
                                           `2208` = "Södermalm",
                                           `2209` = "Enskede-Årsta-Vantör",
                                           `2210` = "Skarpnäck",
                                           `2211` = "Farsta",
                                           `2212` = "Älvsjö",
                                           `2213` = "Hägersten-Liljeholmen",
                                           `2214` = "Skärholmen"
                                           ) )
summary( d_2010$sampling_strata_region )

# sexual identity in 2010
table( d_2010$F10U87G78, useNA = "always" )
d_2010$F10U87G78[ d_2010$F10U87G78 == 9 ] <- NA
d_2010$sexual_identity_2010 <- factor( ifelse( d_2010$F10U87G78 == 1, "Heterosexual",
                                                  ifelse( d_2010$F10U87G78 == 2, "Homosexual",
                                                          ifelse( d_2010$F10U87G78 == 3, "Bisexual", "Other" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ) )
table( d_2010$sexual_identity_2010, useNA = "always" )

# sexual identity in 2014
table( d_2010$F14F103, useNA = "always" )
d_2010$sexual_identity_2014 <- factor( ifelse( d_2010$F14F103 == 1, "Heterosexual",
                                                  ifelse( d_2010$F14F103 == 2, "Homosexual",
                                                          ifelse( d_2010$F14F103 == 3, "Bisexual", "Other" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ) )
table( d_2010$sexual_identity_2014, useNA = "always" )

# sexual identity in 2021
table( d_2010$F21F91, useNA = "always" )
d_2010$sexual_identity_2021 <- factor( ifelse( d_2010$F21F91 == 1, "Heterosexual",
                                                  ifelse( d_2010$F21F91 == 2, "Homosexual",
                                                          ifelse( d_2010$F21F91 == 3, "Bisexual", "Other" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ) )
table( d_2010$sexual_identity_2021, useNA = "always" )

# sex
table( d_2010$kon, useNA = "always" )
d_2010$sex <- factor( ifelse( d_2010$kon == 1, "Male", "Female" ),
                      levels = c( "Male", "Female" ) )
table( d_2010$sex, useNA = "always" )

# age
summary( d_2010$F10alder )
d_2010$age <- d_2010$F10alder
d_2010$age_cat <- categorize_age_group( d_2010$age )
table( d_2010$age_cat, useNA = "always" )

# interaction term between age and sex
d_2010$age_sex <- interaction( d_2010$age_cat, d_2010$sex )

# generation
d_2010$birth_year <- 2010 - d_2010$age
d_2010 <- d_2010 %>%
  mutate( generation = case_when(
    birth_year >= 1981 & birth_year <= 1996 ~ "Millennials (1981–1996)",
    birth_year >= 1965 & birth_year <= 1980 ~ "Generation X (1965–1980)",
    birth_year >= 1946 & birth_year <= 1964 ~ "Baby Boomers (1946–1964)",
    birth_year >= 1928 & birth_year <= 1945 ~ "Silent Generation (1928–1945)",
    birth_year >= 1901 & birth_year <= 1927 ~ "Greatest Generation (1901–1927)"
    ) )

d_2010$generation <- factor( 
  d_2010$generation, 
  levels = c( "Millennials (1981–1996)", "Generation X (1965–1980)", "Baby Boomers (1946–1964)", "Silent Generation (1928–1945)", "Greatest Generation (1901–1927)" ) )
summary( d_2010$generation )

# country of birth
table( d_2010$fodelseland, useNA = "always" )
d_2010$country_of_birth <- factor( ifelse( d_2010$fodelseland == "Sverige", "Sweden",
                                           ifelse( d_2010$fodelseland == "Europa", "Europe", "Outside Europe" ) ),
                                   levels = c( "Sweden", "Europe", "Outside Europe" ) )
table( d_2010$country_of_birth, useNA = "always" )

# education
table( d_2010$utbniva2010, useNA = "always" )
d_2010$education <- factor( ifelse( d_2010$utbniva2010 <= 2, "<=9 years",
                                    ifelse( d_2010$utbniva2010 <= 4, "10-12 years", ">=13 years" ) ), 
                            levels = c( "<=9 years", "10-12 years", ">=13 years" ) )
table( d_2010$education, useNA = "always" )

# occupation
# table( d_2010$SSYK_kl, useNA = "always" )
# d_2010$occupation <- factor(
#   ifelse(
#     d_2010$SSYK_kl == "Yrken inom byggverksamhet och tillverkning" |
#       d_2010$SSYK_kl == "Yrken inom lantbruk, trädgård, skogsbruk och fiske" |
#       d_2010$SSYK_kl == "Yrken inom maskinell tillverkning och transport m.m.",
#     "Manual and field trades",
#     ifelse(
#       d_2010$SSYK_kl == "Service-, omsorgs- och försäljningsyrken" |
#         d_2010$SSYK_kl == "Yrken inom administration och kundtjänst" |
#         d_2010$SSYK_kl == "Yrken med krav på kortare utbildning eller introduktion",
#       "Service and support",
#       ifelse(
#         d_2010$SSYK_kl == "Yrken med krav på fördjupad högskolekompetens" |
#           d_2010$SSYK_kl == "Yrken med krav på högskolekompetens eller motsvarande" |
#           d_2010$SSYK_kl == "Chefsyrken" |
#           d_2010$SSYK_kl == "Militära yrken",
#         "Expertise and leadership",
#         NA
#       )
#     )
#   ),
#   levels = c(
#     "Manual and field trades",
#     "Service and support",
#     "Expertise and leadership"
#   )
# )
# table( d_2010$occupation, useNA = "always" )

# disposable income
summary( d_2010$dispink2010, useNA = "always" )
d_2010$dispink2010 <- d_2010$dispink2010*( 343.19/303.46 ) # Consumer Price Index (CPI)-adjusted income (https://www.statistikdatabasen.scb.se/pxweb/en/ssd/START__PR__PR0101__PR0101L/KPIFastAmed/table/tableViewLayout1/)
d_2010$income <- factor( ifelse( d_2010$dispink2010 <= 2500, "<=2,500",
                                 ifelse( d_2010$dispink2010 > 2500 & d_2010$dispink2010 <= 3500, "(2,500, 3,500]",
                                         ifelse( d_2010$dispink2010 > 3500 & d_2010$dispink2010 <= 4500, "(3,500, 4,500]", ">4,500" ) ) ),
                         levels = c( "<=2,500", "(2,500, 3,500]", "(3,500, 4,500]", ">4,500" ) )
table( d_2010$income, useNA = "always" )

# marital status
table( d_2010$civil2010, useNA = "always" )
d_2010$marital_status <- factor( ifelse( d_2010$civil2010 == "G" | d_2010$civil2010 == "RP", "Currently married",
                                         ifelse( d_2010$civil2010 == "OG", "Never married", "Other" ) ), 
                                 levels = c( "Never married", "Currently married", "Other" ) )
table( d_2010$marital_status, useNA = "always" )


##### demographic characteristics #####

# make characteristics table by sexual identity
explanatory =  c( "sex", "age_cat", "country_of_birth", "education", "income", "marital_status" )
dependent = "sexual_identity_2010"

d_2010_table <- d_2010 %>%
  filter( age <= 29 ) %>%
  summary_factorlist( dependent,
                      explanatory, 
                      na_include = TRUE,
                      na_include_dependent = TRUE, 
                      total_col = TRUE,
                      add_col_totals = TRUE,
                      column = FALSE )

writexl::write_xlsx( d_2010_table, "results_output/characteristics_table_2010.xlsx" )

# # Fisher's test
# x1 <- table( d_2010$sex, d_2010$sexual_identity_2010 )
# x1
# format( round( fisher.test( x1[, c( 1, 2 ) ] )$p.value, 3 ), nsmall = 3 )
# format( round( fisher.test( x1[, c( 1, 3 ) ] )$p.value, 3 ), nsmall = 3 )
# format( round( fisher.test( x1[, c( 1, 4 ) ] )$p.value, 3 ), nsmall = 3 )
# 
# x2 <- table( d_2010$age_cat, d_2010$sexual_identity_2010 )
# x2
# format( round( fisher.test( x2[, c( 1, 2 ) ] )$p.value, 3 ), nsmall = 3 )
# format( round( fisher.test( x2[, c( 1, 3 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
# format( round( fisher.test( x2[, c( 1, 4 ) ] )$p.value, 3 ), nsmall = 3 )
# 
# x3 <- table( d_2010$country_of_birth, d_2010$sexual_identity_2010 )
# x3
# format( round( fisher.test( x3[, c( 1, 2 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
# format( round( fisher.test( x3[, c( 1, 3 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
# format( round( fisher.test( x3[, c( 1, 4 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
# 
# x4 <- table( d_2010$education, d_2010$sexual_identity_2010 )
# x4
# format( round( fisher.test( x4[, c( 1, 2 ) ] )$p.value, 3 ), nsmall = 3 )
# format( round( fisher.test( x4[, c( 1, 3 ) ] )$p.value, 3 ), nsmall = 3 )
# format( round( fisher.test( x4[, c( 1, 4 ) ] )$p.value, 3 ), nsmall = 3 )
# 
# x5 <- table( d_2010$income, d_2010$sexual_identity_2010 )
# x5
# format( round( fisher.test( x5[, c( 1, 2 ) ] )$p.value, 3 ), nsmall = 3 )
# format( round( fisher.test( x5[, c( 1, 3 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
# format( round( fisher.test( x5[, c( 1, 4 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
# 
# x6 <- table( d_2010$marital_status, d_2010$sexual_identity_2010 )
# x6
# format( round( fisher.test( x6[, c( 1, 2 ) ] )$p.value, 3 ), nsmall = 3 )
# format( round( fisher.test( x6[, c( 1, 3 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
# format( round( fisher.test( x6[, c( 1, 4 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )

# x7 <- table( d_2010$occupation, d_2010$sexual_identity_2010 )
# x7
# format( round( fisher.test( x7[, c( 1, 2 ) ] )$p.value, 3 ), nsmall = 3 )
# format( round( fisher.test( x7[, c( 1, 3 ) ] )$p.value, 3 ), nsmall = 3 )
# format( round( fisher.test( x7[, c( 1, 4 ) ] )$p.value, 3 ), nsmall = 3 )


##### design weights #####

summary( d_2010$F10dvikt )
d_2010$design_weight <- d_2010$F10dvikt


##### calibrated weights #####

d_2010$calibrated_weight <- d_2010$F10kalvikt


##### non-response #####

# unit non-response
d_2010$design_weight_unit_nonresponse <- d_2010$F10dbvikt # weights calculated assuming Missing Completely At Random (MCAR) within each stratum
summary( d_2010$design_weight_unit_nonresponse )
sum( d_2010$design_weight_unit_nonresponse ) # No. of source population = 1,601,274

unitresponse_prob <- d_2010 %>% 
  group_by( sampling_strata_region ) %>% 
  summarise( unitresponse_prob = unique( design_weight ) / unique( design_weight_unit_nonresponse ),
             no.of.population = sum( design_weight_unit_nonresponse ),
             sample_size = unique( no.of.population )/unique( design_weight ) ) # calculate overall unit response rate, and no. of population and sample size within each stratum
d_2010 <- d_2010 %>% 
  left_join( unitresponse_prob, by = "sampling_strata_region" )

# item non-response
itemresponse_prob <- d_2010 %>% 
  group_by( sampling_strata_region ) %>% 
  summarise( itemresponse_prob = sum( !is.na( sexual_identity_2010 ) ) / n() ) # calculate item response rate

d_2010 <- d_2010 %>% 
  left_join( itemresponse_prob, by = "sampling_strata_region" ) %>% 
  mutate( itemresponse_prob = ifelse( is.na( sexual_identity_2010 ), 0, itemresponse_prob ) )


##### summary of stratified sampling #####

sampling_frame_2010 <- as.data.frame( d_2010 %>% 
                                   group_by( sampling_strata_region ) %>% 
                                   reframe( no.of.population = unique( no.of.population ), 
                                            sample_size = unique( no.of.population/design_weight ),
                                            unitresponse = n(),
                                            itemresponse = sum( itemresponse_prob != 0 ) ) )

sampling_frame_2010$unitresponse_rate <- sampling_frame_2010$unitresponse/sampling_frame_2010$sample_size
sampling_frame_2010$itemresponse_rate <- sampling_frame_2010$itemresponse/sampling_frame_2010$unitresponse
sampling_frame_2010$overallresponse_rate <- sampling_frame_2010$itemresponse/sampling_frame_2010$sample_size

sampling_frame_2010$unitresponse_label <- paste0( sampling_frame_2010$unitresponse, " (", 
                                             sprintf( "%.1f", sampling_frame_2010$unitresponse_rate*100 ), "%)" )
sampling_frame_2010$overallresponse_label <- paste0( sampling_frame_2010$itemresponse, " (", 
                                                sprintf( "%.1f", sampling_frame_2010$overallresponse_rate*100 ), "%)" )

round( sum( sampling_frame_2010$unitresponse )/( sum( sampling_frame_2010$sample_size ) ), 3 ) # overall unit response rate
round( sum( sampling_frame_2010$itemresponse )/( sum( sampling_frame_2010$unitresponse ) ), 3 ) # overall item response rate
round( sum( sampling_frame_2010$itemresponse )/( sum( sampling_frame_2010$sample_size ) ), 3 ) # overall response rate

writexl::write_xlsx( sampling_frame_2010, "results_output/sampling_frame_2010.xlsx" )


##### replicating non-respondent rows for sampling design #####

# because d_2010 includes data only for respondents (unit response), we need to duplicate rows for non-respondents
# so that the final dataset represents the sampling process
rows_to_add <- d_2010 %>%
  group_by( sampling_strata_region ) %>%
  summarise( to_add = unique( sample_size ) - n(),
             no.of.population = unique( no.of.population ),
             sample_size = unique( sample_size ),
             design_weight = unique( design_weight ) )

rows_to_add$to_add <- round( rows_to_add$to_add )

sum( rows_to_add$to_add ) # 24,574 non-respondents

replicated_rows <- rows_to_add[ rep( row.names( rows_to_add ), rows_to_add$to_add ), c( 1, 3:5 ) ]

d_2010_complete <- bind_rows( d_2010, replicated_rows ) # 55,341 individuals in the original sample

d_2010_complete <- d_2010_complete[ , c( 1, 16, 17, 19, 30:50 ) ]
summary( d_2010_complete )
```

### 3. Mental Health Outcomes
#### 3.1. Self-reported
```{r}
# recent psychological distress
table( d_2010_complete$F10GHQ12, useNA = "always" )
d_2010_complete$psychological_distress <- factor( ifelse( d_2010_complete$F10GHQ12 >= 3, "Yes", "No" ),
                                                  levels = c( "Yes", "No" ) ) # psychological distress defined as a score >= 3
table( d_2010_complete$psychological_distress, useNA = "always" )

# suicidal thoughts
table( d_2010_complete$F10U51G55, useNA = "always" )
d_2010_complete$F10U51G55[ d_2010_complete$F10U51G55 == 9 ] <- NA
d_2010_complete$suicidal_thoughts <- factor( 
  case_when(
    d_2010_complete$F10U51G55 == 1 ~ "No",
    d_2010_complete$F10U51G55 %in% c( 2, 3, 4 ) ~ "Yes" ),
  levels = c( "Yes", "No" ) )
table( d_2010_complete$suicidal_thoughts, useNA = "always" )

# suicide attempts
table( d_2010_complete$F10U52G56, useNA = "always" )
d_2010_complete$F10U52G56[ d_2010_complete$F10U52G56 == 9 ] <- NA
d_2010_complete$suicide_attempts <- factor( 
  case_when(
    d_2010_complete$F10U52G56 == 1 ~ "No",
    d_2010_complete$F10U52G56 %in% c( 2, 3, 4 ) ~ "Yes" ),
  levels = c( "Yes", "No" ) )
table( d_2010_complete$suicide_attempts, useNA = "always" )
```

#### 3.2. Registry-based
##### 3.2.1. Check migration events
```{r}
load('/Volumes/projects/LGBT Project data/Swedish Registers/dates_all.RData') # cleaned migration data
summary( dates_all )

eligible_dates <- dates_all %>%
  filter( lopnr %in% d_2010_complete$lopnr )
summary( eligible_dates )
length( unique( eligible_dates$lopnr ) )

followup_start <- as.Date( "2010-01-01" )
followup_end <- as.Date( "2010-12-31" )

move_in_ids <- eligible_dates %>%
  filter( date < followup_start ) %>%
  arrange( lopnr, date ) %>%
  group_by( lopnr ) %>%
  slice_tail( n = 1 ) %>%
  ungroup() %>%
  filter( event_type == "move-in" ) %>%
  pull( lopnr )

had_event_ids <- eligible_dates %>%
  filter( lopnr %in% move_in_ids, 
          date >= followup_start, 
          date <= followup_end ) %>%
  pull( lopnr ) %>%
  unique()

move_in_before_year_ids <- setdiff( move_in_ids, had_event_ids )

move_out_after_year_ids <- eligible_dates %>%
  arrange( lopnr, date ) %>%
  group_by( lopnr ) %>%
  slice( 1 ) %>%
  ungroup() %>%
  filter( date > followup_end,
          event_type %in% c( "move-out", "death" ) ) %>%
  pull( lopnr )

included_year_ids <- union( move_in_before_year_ids, move_out_after_year_ids ) # among those who had any migration event

excluded_year_ids <- eligible_dates %>%
  filter( !lopnr %in% included_year_ids ) %>%
  pull( lopnr ) %>%
  unique() # identify participants who were not continuously registered in 2010

eligible_dates %>%
  filter( lopnr %in% excluded_year_ids,
          date <= followup_end ) %>%
  count( event_type ) # no death event by the end of 2010
```

##### 3.2.2. Use of antidepressants and anxiolytics
```{r}
# dispensed prescription: antidepressants (N06A) and anxiolytics (N05B)
atc_2002_2014 <- read_sas('/Volumes/projects/LGBT Project data/Swedish Registers/atc_pdr_2002_2014.sas7bdat') %>%
  filter( !grepl( "^N05CD", ATC ) ) %>%
  rename( dispense_date = EDATUM )
summary( atc_2002_2014 )
unique( atc_2002_2014$ATC )

atc_2010 <- atc_2002_2014 %>%
  mutate( drug_class = as.factor( case_when(
    grepl( "^N06A", ATC ) ~ "N06A",
    grepl( "^N05B", ATC ) ~ "N05B" ) ),
    year = year( dispense_date ) ) %>%
  select( lopnr, drug_class, year ) %>%
  filter( lopnr %in% d_2010_complete$lopnr, # select SPHC-B 2010 participants
          year == 2010 ) # select prescription data for the year 2010

atc_2010_summary <- atc_2010 %>%
  group_by( lopnr, drug_class ) %>%
  summarise( count = n(), .groups = "drop" )

atc_2010_summary_wide <- atc_2010_summary %>%
  pivot_wider(
    names_from = drug_class,
    values_from = count,
    names_prefix = "count_",
    values_fill = 0 ) %>%
  mutate(
    used_N05B = factor( if_else( count_N05B > 0, "Yes", "No" ) ),
    used_N06A = factor( if_else( count_N06A > 0, "Yes", "No" ) ) )

summary( atc_2010_summary_wide )

length( intersect( atc_2010_summary_wide$lopnr, excluded_year_ids ) ) # 6 excluded participants had prescription data, so their prevalence data will be treated as observed

reincluded_year_ids_N06A <- atc_2010_summary_wide %>%
  filter( lopnr %in% excluded_year_ids,
          used_N06A == "Yes" ) %>%
  pull( lopnr ) # 4 had dispensed prescription of antidepressants

reincluded_year_ids_N05B <- atc_2010_summary_wide %>%
  filter( lopnr %in% excluded_year_ids,
          used_N05B == "Yes" ) %>%
  pull( lopnr ) # 3 had dispensed prescription of anxiolytics
```

#### 3.3. Construct study sample
```{r}
d_2010_complete <- d_2010_complete %>%
  left_join( atc_2010_summary_wide, by = "lopnr" ) %>%
  mutate(
    count_N05B = if_else( !is.na( lopnr ) & is.na( count_N05B ), 0, count_N05B ),
    count_N06A = if_else( !is.na( lopnr ) & is.na( count_N06A ), 0, count_N06A ),
    used_N05B = factor( if_else( !is.na( lopnr ) & is.na( used_N05B ), "No", used_N05B ) ),
    used_N06A = factor( if_else( !is.na( lopnr ) & is.na( used_N06A ), "No", used_N06A ) )
    ) # assume complete follow-up in 2010

summary( d_2010_complete )

d_2010_complete <- d_2010_complete %>%
  mutate( 
    used_N06A = if_else(
      !is.na( lopnr ) & lopnr %in% setdiff( excluded_year_ids, reincluded_year_ids_N06A ),
      NA,
      used_N06A
    ),
    
    used_N05B = if_else(
      !is.na( lopnr ) & lopnr %in% setdiff( excluded_year_ids, reincluded_year_ids_N05B ),
      NA,
      used_N05B
    ),
    
    count_N06A = if_else(
      !is.na( lopnr ) & lopnr %in% excluded_year_ids,
      NA,
      count_N06A
    ),
    
    count_N05B = if_else(
      !is.na( lopnr ) & lopnr %in% excluded_year_ids,
      NA,
      count_N05B
      ),
    
    followup_2010 = as.factor( 
      if_else( is.na( lopnr ), NA_character_,
               if_else( lopnr %in% excluded_year_ids, "No", "Yes" ) ) 
      )
    )

summary( d_2010_complete )

miss_var_summary(
  d_2010_complete %>%
    filter( !is.na( lopnr ) ) ) %>%
  filter( n_miss > 0 ) %>%
  print( n = Inf )
```

### 4. Complete-Case Analysis
```{r}
variables_list <- list(
  list( variable = "used_N06A", condition = "Yes", name = "antidepressant" ),
  list( variable = "used_N05B", condition = "Yes", name = "anxiolytic" ),
  list( variable = "psychological_distress", condition = "Yes", name = "psychological_distress" ),
  list( variable = "suicidal_thoughts", condition = "Yes", name = "suicidal_thoughts" ),
  list( variable = "suicide_attempts", condition = "Yes", name = "suicide_attempts" )
  )

########## Prevalence ##########

# create survey design
survey_design_cc <- svydesign( ids = ~ 1, 
                               strata = ~ sampling_strata_region,
                               weights = ~ design_weight,
                               fpc = ~ no.of.population,
                               data = d_2010_complete )

# overall prevalence
overall_list <- cal_prev_indi_overall_cc( variables_list = variables_list,
                                          design = subset( survey_design_cc, age <= 29 ),
                                          year = 2010 )

overall_prevalence_2010 <- Reduce( cbind, overall_list ) %>%
  mutate( sexual_identity = "Stockholm County" ) %>%
  relocate( sexual_identity )

writexl::write_xlsx( overall_prevalence_2010, "results_output/results_cc/overall_prevalence_2010_cc.xlsx" )

# by sexual identity
results_list <- cal_prev_indi_cc( variables_list = variables_list, 
                                  design = subset( survey_design_cc, age <= 29 ), 
                                  year = 2010, 
                                  group_var = "sexual_identity_2010" )

prevalence_2010 <- Reduce( function( x, y ){
  merge( x, y, by = "sexual_identity_2010" )
}, 
results_list )

writexl::write_xlsx( prevalence_2010, "results_output/results_cc/prevalence_2010_by_identity_cc.xlsx" )

# by sex
results_list_by_sex <- cal_prev_indi_cc( variables_list = variables_list,
                                         design = subset( survey_design_cc, age <= 29 ),
                                         year = 2010,
                                         group_var = "sexual_identity_2010 + sex",
                                         subgroup = TRUE )

prevalence_2010_by_sex <- Reduce( function( x, y ){
  merge( x, y, by = c( "sexual_identity_2010", "sex" ) )
},
results_list_by_sex )

writexl::write_xlsx( prevalence_2010_by_sex, "results_output/results_cc/prevalence_2010_by_sex_cc.xlsx" )

# by generation
results_list_by_generation <- cal_prev_indi_cc( variables_list = variables_list,
                                                design = subset( survey_design_cc, age <= 29 ),
                                                year = 2010,
                                                group_var = "sexual_identity_2010 + generation",
                                                subgroup = TRUE )

prevalence_2010_by_generation <- Reduce( function( x, y ){
  merge( x, y, by = c( "sexual_identity_2010", "generation" ) )
}, 
results_list_by_generation )

writexl::write_xlsx( prevalence_2010_by_generation, "results_output/results_cc/prevalence_2010_by_generation_cc.xlsx" )


########## Prevalence Ratio ##########

str( d_2010_complete )

# create survey design
survey_design_cc <- svydesign( ids = ~ 1, 
                               strata = ~ sampling_strata_region,
                               weights = ~ design_weight,
                               fpc = ~ no.of.population,
                               data = d_2010_complete %>%
                                 mutate( used_N05B = ifelse( used_N05B == "Yes", 1, 0 ),
                                         used_N06A = ifelse( used_N06A == "Yes", 1, 0 ),
                                         psychological_distress = ifelse( psychological_distress == "Yes", 1, 0 ),
                                         suicidal_thoughts = ifelse( suicidal_thoughts == "Yes", 1, 0 ),
                                         suicide_attempts = ifelse( suicide_attempts == "Yes", 1, 0 ) ) )

# crude analysis (overall)
models_list_crude <- cal_pr_indi_cc( 
  design = subset( survey_design_cc, age <= 29 ), 
  exposure = "sexual_identity_2010", 
  outcome_list = variables_list,
  year = 2010 )

# adjusted analysis (overall)
models_list_adjusted <- cal_pr_indi_cc( 
  design = subset( survey_design_cc, age <= 29 ), 
  exposure = "sexual_identity_2010", 
  outcome_list = variables_list,
  covariates = "age + sex + country_of_birth",
  year = 2010 )

pr_crude_cc <- extract_pr_cc(
  model_list = models_list_crude,
  exposure_var = "sexual_identity_2010" ) %>%
  mutate( model_type = "crude" )

pr_adjusted_cc <- extract_pr_cc(
  model_list = models_list_adjusted,
  exposure_var = "sexual_identity_2010" ) %>%
  mutate( model_type = "adjusted" )

pr_2010_cc <- bind_rows( pr_crude_cc, pr_adjusted_cc )
writexl::write_xlsx( pr_2010_cc, "results_output/results_cc/pr_2010_cc.xlsx" )

# crude analysis (MALE)
levels( d_2010_complete$sex )

models_list_male_crude <- cal_pr_indi_cc( 
  design = subset( survey_design_cc, age <= 29 ), 
  exposure = "sexual_identity_2010 * sex", 
  outcome_list = variables_list,
  year = 2010 )

# adjusted analysis (MALE)
models_list_male_adjusted <- cal_pr_indi_cc( 
  design = subset( survey_design_cc, age <= 29 ), 
  exposure = "sexual_identity_2010 * sex", 
  outcome_list = variables_list,
  covariates = "age + country_of_birth",
  year = 2010 )

summary( models_list_male_crude[[ 1 ]] ) # random check
summary( models_list_male_adjusted[[ 1 ]] ) # random check

pr_male_crude_cc <- extract_pr_by_sex_cc(
  model_list = models_list_male_crude,
  exposure_var = "sexual_identity_2010" ) %>%
  mutate( model_type = "crude",
          sex = "Male" )

pr_male_adjusted_cc <- extract_pr_by_sex_cc(
  model_list = models_list_male_adjusted,
  exposure_var = "sexual_identity_2010" ) %>%
  mutate( model_type = "adjusted",
          sex = "Male" )

pr_male_2010_cc <- bind_rows( pr_male_crude_cc, pr_male_adjusted_cc )
writexl::write_xlsx( pr_male_2010_cc, "results_output/results_cc/pr_male_2010_cc.xlsx" )


# create survey design
survey_design_cc <- svydesign( ids = ~ 1, 
                               strata = ~ sampling_strata_region,
                               weights = ~ design_weight,
                               fpc = ~ no.of.population,
                               data = d_2010_complete %>%
                                 mutate( sex = factor( sex, levels = c( "Female", "Male" ) ),
                                         used_N05B = ifelse( used_N05B == "Yes", 1, 0 ),
                                         used_N06A = ifelse( used_N06A == "Yes", 1, 0 ),
                                         psychological_distress = ifelse( psychological_distress == "Yes", 1, 0 ),
                                         suicidal_thoughts = ifelse( suicidal_thoughts == "Yes", 1, 0 ),
                                         suicide_attempts = ifelse( suicide_attempts == "Yes", 1, 0 ) ) )

# crude analysis (FEMALE)
models_list_female_crude <- cal_pr_indi_cc( 
  design = subset( survey_design_cc, age <= 29 ), 
  exposure = "sexual_identity_2010 * sex", 
  outcome_list = variables_list,
  year = 2010 )

# adjusted analysis (FEMALE)
models_list_female_adjusted <- cal_pr_indi_cc( 
  design = subset( survey_design_cc, age <= 29 ), 
  exposure = "sexual_identity_2010 * sex", 
  outcome_list = variables_list,
  covariates = "age + country_of_birth",
  year = 2010 )

summary( models_list_female_crude[[ 1 ]] ) # random check
summary( models_list_female_adjusted[[ 1 ]] )

pr_female_crude_cc <- extract_pr_by_sex_cc(
  model_list = models_list_female_crude,
  exposure_var = "sexual_identity_2010" ) %>%
  mutate( model_type = "crude",
          sex = "Female" )

pr_female_adjusted_cc <- extract_pr_by_sex_cc(
  model_list = models_list_female_adjusted,
  exposure_var = "sexual_identity_2010" ) %>%
  mutate( model_type = "adjusted",
          sex = "Female" )

pr_female_2010_cc <- bind_rows( pr_female_crude_cc, pr_female_adjusted_cc )
writexl::write_xlsx( pr_female_2010_cc, "results_output/results_cc/pr_female_2010_cc.xlsx" )


########## Prevalence Difference ##########

str( d_2010_complete )

# create survey design
survey_design_cc <- svydesign( ids = ~ 1, 
                               strata = ~ sampling_strata_region,
                               weights = ~ design_weight,
                               fpc = ~ no.of.population,
                               data = d_2010_complete %>%
                                 mutate( used_N05B = ifelse( used_N05B == "Yes", 1, 0 ),
                                         used_N06A = ifelse( used_N06A == "Yes", 1, 0 ),
                                         psychological_distress = ifelse( psychological_distress == "Yes", 1, 0 ),
                                         suicidal_thoughts = ifelse( suicidal_thoughts == "Yes", 1, 0 ),
                                         suicide_attempts = ifelse( suicide_attempts == "Yes", 1, 0 ) ) )

# crude analysis (overall)
models_list_crude <- cal_pd_indi_cc( 
  design = subset( survey_design_cc, age <= 29 ), 
  exposure = "sexual_identity_2010", 
  outcome_list = variables_list,
  year = 2010 )

# adjusted analysis (overall)
models_list_adjusted <- cal_pd_indi_cc( 
  design = subset( survey_design_cc, age <= 29 ), 
  exposure = "sexual_identity_2010", 
  outcome_list = variables_list,
  covariates = "age + sex + country_of_birth",
  year = 2010 )

pd_crude_cc <- extract_pd_cc(
  model_list = models_list_crude,
  exposure_var = "sexual_identity_2010" ) %>%
  mutate( model_type = "crude" )

pd_adjusted_cc <- extract_pd_cc(
  model_list = models_list_adjusted,
  exposure_var = "sexual_identity_2010" ) %>%
  mutate( model_type = "adjusted" )

pd_2010_cc <- bind_rows( pd_crude_cc, pd_adjusted_cc )
writexl::write_xlsx( pd_2010_cc, "results_output/results_cc/pd_2010_cc.xlsx" )

# crude analysis (MALE)
levels( d_2010_complete$sex )

models_list_male_crude <- cal_pd_indi_cc( 
  design = subset( survey_design_cc, age <= 29 ), 
  exposure = "sexual_identity_2010 * sex", 
  outcome_list = variables_list,
  year = 2010 )

# adjusted analysis (MALE)
models_list_male_adjusted <- cal_pd_indi_cc( 
  design = subset( survey_design_cc, age <= 29 ), 
  exposure = "sexual_identity_2010 * sex", 
  outcome_list = variables_list,
  covariates = "age + country_of_birth",
  year = 2010 )

summary( models_list_male_crude[[ 1 ]] ) # random check
summary( models_list_male_adjusted[[ 1 ]] ) # random check

pd_male_crude_cc <- extract_pd_by_sex_cc(
  model_list = models_list_male_crude,
  exposure_var = "sexual_identity_2010" ) %>%
  mutate( model_type = "crude",
          sex = "Male" )

pd_male_adjusted_cc <- extract_pd_by_sex_cc(
  model_list = models_list_male_adjusted,
  exposure_var = "sexual_identity_2010" ) %>%
  mutate( model_type = "adjusted",
          sex = "Male" )

pd_male_2010_cc <- bind_rows( pd_male_crude_cc, pd_male_adjusted_cc )
writexl::write_xlsx( pd_male_2010_cc, "results_output/results_cc/pd_male_2010_cc.xlsx" )


# create survey design
survey_design_cc <- svydesign( ids = ~ 1, 
                               strata = ~ sampling_strata_region,
                               weights = ~ design_weight,
                               fpc = ~ no.of.population,
                               data = d_2010_complete %>%
                                 mutate( sex = factor( sex, levels = c( "Female", "Male" ) ),
                                         used_N05B = ifelse( used_N05B == "Yes", 1, 0 ),
                                         used_N06A = ifelse( used_N06A == "Yes", 1, 0 ),
                                         psychological_distress = ifelse( psychological_distress == "Yes", 1, 0 ),
                                         suicidal_thoughts = ifelse( suicidal_thoughts == "Yes", 1, 0 ),
                                         suicide_attempts = ifelse( suicide_attempts == "Yes", 1, 0 ) ) )

# crude analysis (FEMALE)
models_list_female_crude <- cal_pd_indi_cc( 
  design = subset( survey_design_cc, age <= 29 ), 
  exposure = "sexual_identity_2010 * sex", 
  outcome_list = variables_list,
  year = 2010 )

# adjusted analysis (FEMALE)
models_list_female_adjusted <- cal_pd_indi_cc( 
  design = subset( survey_design_cc, age <= 29 ), 
  exposure = "sexual_identity_2010 * sex", 
  outcome_list = variables_list,
  covariates = "age + country_of_birth",
  year = 2010 )

summary( models_list_female_crude[[ 1 ]] ) # random check
summary( models_list_female_adjusted[[ 1 ]] )

pd_female_crude_cc <- extract_pd_by_sex_cc(
  model_list = models_list_female_crude,
  exposure_var = "sexual_identity_2010" ) %>%
  mutate( model_type = "crude",
          sex = "Female" )

pd_female_adjusted_cc <- extract_pd_by_sex_cc(
  model_list = models_list_female_adjusted,
  exposure_var = "sexual_identity_2010" ) %>%
  mutate( model_type = "adjusted",
          sex = "Female" )

pd_female_2010_cc <- bind_rows( pd_female_crude_cc, pd_female_adjusted_cc )
writexl::write_xlsx( pd_female_2010_cc, "results_output/results_cc/pd_female_2010_cc.xlsx" )
```