---
title: "Sexual identity and mental health outcomes among adolescents and young adults in Stockholm County, SPHC-B 2002"
author: Willi Zhang
email: willi.zhang@ki.se
output: html_notebook
editor_options: 
  chunk_output_type: console
---

### 1. Load Packages
```{r}
library(haven)
library(tidyverse)
library(finalfit)
library(lubridate)
library(naniar)
library(jomo)
library(mitml)
library(mitools)
library(survey)
library(svyVGAM)
library(vcd)
library(rcompanion)
source('helper_functions.R') # helper function
```

### 2. Import and Prepare Data
```{r}
d_2002 <- read_sas('/Volumes/projects/LGBT Project data/sphc02_07_10_14_21.sas7bdat')
summary( d_2002$lopnr ) # 7,411 did not participate in the 2007 follow-up survey where written informed consent for registry linkage was sought
table( d_2002$population )

# sampling strata
n_miss( d_2002$stratum )
d_2002$sampling_strata <- as.factor( d_2002$stratum )
length( unique( d_2002$sampling_strata ) )

d_2002 <- d_2002 %>%
  mutate( sampling_strata_region = recode( sampling_strata, 
                                           `101` = "Upplands-Väsby",
                                           `102` = "Vallentuna",
                                           `103` = "Österåker",
                                           `104` = "Värmdö",
                                           `105` = "Järfälla",
                                           `106` = "Ekerö",
                                           `107` = "Huddinge",
                                           `108` = "Botkyrka",
                                           `109` = "Salem",
                                           `110` = "Haninge",
                                           `111` = "Tyresö",
                                           `112` = "Upplands-Bro",
                                           `113` = "Nykvarn",
                                           `114` = "Täby",
                                           `115` = "Danderyd",
                                           `116` = "Sollentuna",
                                           `117` = "Södertälje",
                                           `118` = "Nacka",
                                           `119` = "Sundbyberg",
                                           `120` = "Solna",
                                           `121` = "Lidingö",
                                           `122` = "Vaxholm",
                                           `123` = "Norrtälje",
                                           `124` = "Sigtuna",
                                           `125` = "Nynäshamn",
                                           `201` = "Kista",
                                           `202` = "Rinkeby",
                                           `203` = "Spånga-Tensta",
                                           `204` = "Hässelby-Vällingby",
                                           `205` = "Bromma",
                                           `206` = "Kungsholmen",
                                           `207` = "Norrmalm",
                                           `208` = "Östermalm",
                                           `209` = "Maria-Gamla Stan",
                                           `210` = "Katarina-Sofia",
                                           `211` = "Enskede-Årsta",
                                           `212` = "Skarpnäck",
                                           `213` = "Farsta",
                                           `214` = "Vantör",
                                           `215` = "Älvsjö",
                                           `216` = "Liljeholmen",
                                           `217` = "Hägersten",
                                           `218` = "Skärholmen",
                                           `998` = "Unknown",
                                           `999` = "Unknown"
                                           ) )
summary( d_2002$sampling_strata_region )

# sex
table( d_2002$kon, useNA = "always" )
d_2002$sex <- factor( ifelse( d_2002$kon == 1, "Male", "Female" ),
                      levels = c( "Male", "Female" ) )
table( d_2002$sex, useNA = "always" )

d_2002$sampling_strata_region <- interaction( d_2002$sampling_strata_region, d_2002$sex )
length( unique( d_2002$sampling_strata_region ) ) # 88 strata

# sexual identity in 2010
table( d_2002$F10F103, useNA = "always" )
d_2002$F10F103[ d_2002$F10F103 == 9 ] <- NA
d_2002$sexual_identity_2010 <- factor( ifelse( d_2002$F10F103 == 1, "Heterosexual",
                                                  ifelse( d_2002$F10F103 == 2, "Homosexual",
                                                          ifelse( d_2002$F10F103 == 3, "Bisexual", "Other" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ) )
table( d_2002$sexual_identity_2010, useNA = "always" )

# sexual identity in 2014
table( d_2002$F14F103, useNA = "always" )
d_2002$sexual_identity_2014 <- factor( ifelse( d_2002$F14F103 == 1, "Heterosexual",
                                                  ifelse( d_2002$F14F103 == 2, "Homosexual",
                                                          ifelse( d_2002$F14F103 == 3, "Bisexual", "Other" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ) )
table( d_2002$sexual_identity_2014, useNA = "always" )

# sexual identity in 2021
table( d_2002$F21F91, useNA = "always" )
d_2002$sexual_identity_2021 <- factor( ifelse( d_2002$F21F91 == 1, "Heterosexual",
                                                  ifelse( d_2002$F21F91 == 2, "Homosexual",
                                                          ifelse( d_2002$F21F91 == 3, "Bisexual", "Other" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ) )
table( d_2002$sexual_identity_2021, useNA = "always" )

# age
summary( d_2002$F2alder )
d_2002$age <- d_2002$F2alder
d_2002$age_cat <- categorize_age_group( d_2002$age )
table( d_2002$age_cat, useNA = "always" )

# interaction term between age and sex
d_2002$age_sex <- interaction( d_2002$age_cat, d_2002$sex )

# generation
d_2002$birth_year <- 2002 - d_2002$age
summary( d_2002$birth_year )
d_2002 <- d_2002 %>%
  mutate( generation = case_when(
    birth_year >= 1981 & birth_year <= 1996 ~ "Millennials (1981–1996)",
    birth_year >= 1965 & birth_year <= 1980 ~ "Generation X (1965–1980)",
    birth_year >= 1946 & birth_year <= 1964 ~ "Baby Boomers (1946–1964)",
    birth_year >= 1928 & birth_year <= 1945 ~ "Silent Generation (1928–1945)",
    birth_year >= 1901 & birth_year <= 1927 ~ "Greatest Generation (1901–1927)"
    ) )

d_2002$generation <- factor( 
  d_2002$generation, 
  levels = c( "Millennials (1981–1996)", "Generation X (1965–1980)", "Baby Boomers (1946–1964)", "Silent Generation (1928–1945)", "Greatest Generation (1901–1927)" ) )
summary( d_2002$generation )

# country of birth
table( d_2002$fodelseland, useNA = "always" )
d_2002$fodelseland[ d_2002$fodelseland == "" ] <- NA
d_2002$country_of_birth <- factor( ifelse( d_2002$fodelseland == "Sverige", "Sweden",
                                           ifelse( d_2002$fodelseland == "Europa", "Europe", "Outside Europe" ) ),
                                   levels = c( "Sweden", "Europe", "Outside Europe" ) )
table( d_2002$country_of_birth, useNA = "always" )

# education
table( d_2002$utbniva2002, useNA = "always" )
d_2002$education <- factor( ifelse( d_2002$utbniva2002 <= 2, "<=9 years",
                                    ifelse( d_2002$utbniva2002 <= 4, "10-12 years", ">=13 years" ) ), 
                            levels = c( "<=9 years", "10-12 years", ">=13 years" ) )
table( d_2002$education, useNA = "always" )

# disposable income
summary( d_2002$dispink2002, useNA = "always" )
d_2002$dispink2002[ d_2002$dispink2002 < 0 ] <- NA
d_2002$dispink2002 <- d_2002$dispink2002*( 343.19/272.80 ) # Consumer Price Index (CPI)-adjusted income (https://www.statistikdatabasen.scb.se/pxweb/en/ssd/START__PR__PR0101__PR0101L/KPIFastAmed/table/tableViewLayout1/)
d_2002$income <- factor( ifelse( d_2002$dispink2002 <= 2500, "<=2,500",
                                 ifelse( d_2002$dispink2002 > 2500 & d_2002$dispink2002 <= 3500, "(2,500, 3,500]",
                                         ifelse( d_2002$dispink2002 > 3500 & d_2002$dispink2002 <= 4500, "(3,500, 4,500]", ">4,500" ) ) ),
                         levels = c( "<=2,500", "(2,500, 3,500]", "(3,500, 4,500]", ">4,500" ) )
table( d_2002$income, useNA = "always" )

# marital status
table( d_2002$civil2002, useNA = "always" )
d_2002$civil2002[ d_2002$civil2002 == "" ] <- NA
d_2002$marital_status <- factor( ifelse( d_2002$civil2002 == "G" | d_2002$civil2002 == "RP", "Currently married",
                                         ifelse( d_2002$civil2002 == "OG", "Never married", "Other" ) ), 
                                 levels = c( "Never married", "Currently married", "Other" ) )
table( d_2002$marital_status, useNA = "always" )


##### demographic characteristics #####

# make characteristics table by sexual identity
explanatory =  c( "age", "sex", "country_of_birth", "education", "income", "marital_status" )
dependent = "sexual_identity_2010"

d_2002_table <- d_2002 %>% 
  filter( age <= 29 ) %>%
  summary_factorlist( dependent,
                      explanatory, 
                      na_include = TRUE,
                      na_include_dependent = TRUE, 
                      total_col = TRUE,
                      add_col_totals = TRUE,
                      column = FALSE )

writexl::write_xlsx( d_2002_table, "results_output/characteristics_table_2002.xlsx" )

# d_2002_young <- d_2002 %>% 
#   filter( age <= 29 )
# 
# # Fisher's test
# x1 <- table( d_2002_young$sex, d_2002_young$sexual_identity_2010 )
# x1
# format( round( fisher.test( x1[, c( 1, 2 ) ] )$p.value, 3 ), nsmall = 3 )
# format( round( fisher.test( x1[, c( 1, 3 ) ] )$p.value, 3 ), nsmall = 3 )
# format( round( fisher.test( x1[, c( 1, 4 ) ] )$p.value, 3 ), nsmall = 3 )
# 
# x2 <- table( d_2002_young$age_cat, d_2002_young$sexual_identity_2010 )
# x2
# format( round( fisher.test( x2[, c( 1, 2 ) ] )$p.value, 3 ), nsmall = 3 )
# format( round( fisher.test( x2[, c( 1, 3 ) ] )$p.value, 3 ), nsmall = 3 )
# format( round( fisher.test( x2[, c( 1, 4 ) ] )$p.value, 3 ), nsmall = 3 )
# 
# x3 <- table( d_2002_young$country_of_birth, d_2002_young$sexual_identity_2010 )
# x3
# format( round( fisher.test( x3[, c( 1, 2 ) ] )$p.value, 3 ), nsmall = 3 )
# format( round( fisher.test( x3[, c( 1, 3 ) ] )$p.value, 3 ), nsmall = 3 )
# format( round( fisher.test( x3[, c( 1, 4 ) ] )$p.value, 3 ), nsmall = 3 )
# 
# x4 <- table( d_2002_young$education, d_2002_young$sexual_identity_2010 )
# x4
# format( round( fisher.test( x4[, c( 1, 2 ) ] )$p.value, 3 ), nsmall = 3 )
# format( round( fisher.test( x4[, c( 1, 3 ) ] )$p.value, 3 ), nsmall = 3 )
# format( round( fisher.test( x4[, c( 1, 4 ) ] )$p.value, 3 ), nsmall = 3 )
# 
# x5 <- table( d_2002_young$income, d_2002_young$sexual_identity_2010 )
# x5
# format( round( fisher.test( x5[, c( 1, 2 ) ] )$p.value, 3 ), nsmall = 3 )
# format( round( fisher.test( x5[, c( 1, 3 ) ] )$p.value, 3 ), nsmall = 3 )
# format( round( fisher.test( x5[, c( 1, 4 ) ] )$p.value, 3 ), nsmall = 3 )
# 
# x6 <- table( d_2002_young$marital_status, d_2002_young$sexual_identity_2010 )
# x6
# format( round( fisher.test( x6[, c( 1, 2 ) ] )$p.value, 3 ), nsmall = 3 )
# format( round( fisher.test( x6[, c( 1, 3 ) ] )$p.value, 3 ), nsmall = 3 )
# format( round( fisher.test( x6[, c( 1, 4 ) ] )$p.value, 3 ), nsmall = 3 )


##### design weights #####

summary( d_2002$F2dvikt )
d_2002$design_weight <- d_2002$F2dvikt


##### calibrated weights #####

d_2002$calibrated_weight <- d_2002$F2kalvikt


##### non-response #####

# unit non-response
d_2002$design_weight_unit_nonresponse <- d_2002$F2dbvikt # weights calculated assuming Missing Completely At Random (MCAR) within each stratum
summary( d_2002$design_weight_unit_nonresponse )
sum( d_2002$design_weight_unit_nonresponse ) # No. of source population = 1,402,160

unitresponse_prob <- d_2002 %>% 
  group_by( sampling_strata_region ) %>% 
  summarise( unitresponse_prob = unique( design_weight ) / unique( design_weight_unit_nonresponse ),
             no.of.population = sum( design_weight_unit_nonresponse ),
             sample_size = unique( no.of.population )/unique( design_weight ) ) # calculate overall unit response rate, and no. of population and sample size within each stratum
d_2002 <- d_2002 %>% 
  left_join( unitresponse_prob, by = "sampling_strata_region" )

# item non-response
itemresponse_prob <- d_2002 %>% 
  group_by( sampling_strata_region ) %>% 
  summarise( itemresponse_prob = sum( !is.na( sexual_identity_2010 ) ) / n() ) # calculate item response rate

d_2002 <- d_2002 %>% 
  left_join( itemresponse_prob, by = "sampling_strata_region" ) %>% 
  mutate( itemresponse_prob = ifelse( is.na( sexual_identity_2010 ), 0, itemresponse_prob ) )


##### summary of stratified sampling #####

sampling_frame_2002 <- as.data.frame( d_2002 %>%
                                        group_by( sampling_strata_region ) %>%
                                        reframe( no.of.population = unique( no.of.population ),
                                                 sample_size = unique( no.of.population/design_weight ),
                                                 unitresponse = n(),
                                                 itemresponse = sum( itemresponse_prob != 0 ) ) )

sampling_frame_2002$unitresponse_rate <- sampling_frame_2002$unitresponse/sampling_frame_2002$sample_size
sampling_frame_2002$itemresponse_rate <- sampling_frame_2002$itemresponse/sampling_frame_2002$unitresponse
sampling_frame_2002$overallresponse_rate <- sampling_frame_2002$itemresponse/sampling_frame_2002$sample_size

sampling_frame_2002$unitresponse_label <- paste0( sampling_frame_2002$unitresponse, " (", 
                                             sprintf( "%.1f", sampling_frame_2002$unitresponse_rate*100 ), "%)" )
sampling_frame_2002$overallresponse_label <- paste0( sampling_frame_2002$itemresponse, " (", 
                                                sprintf( "%.1f", sampling_frame_2002$overallresponse_rate*100 ), "%)" )

round( sum( sampling_frame_2002$unitresponse )/( sum( sampling_frame_2002$sample_size ) ), 3 ) 
round( sum( sampling_frame_2002$itemresponse )/( sum( sampling_frame_2002$unitresponse ) ), 3 ) 
round( sum( sampling_frame_2002$itemresponse )/( sum( sampling_frame_2002$sample_size ) ), 3 ) 

sampling_frame_2002 %>%
  mutate( sex = str_extract( sampling_strata_region, "Male|Female" ) ) %>%
  group_by( sex ) %>%
  summarise(
    unit_response_rate = round( sum( unitresponse ) / sum( sample_size ), 3 ),
    item_response_rate = round( sum( itemresponse ) / sum( unitresponse ), 3 ),
    overall_response_rate = round( sum( itemresponse ) / sum( sample_size ), 3 )
    )

writexl::write_xlsx( sampling_frame_2002, "results_output/sampling_frame_2002.xlsx" )


##### replicating non-respondent rows for sampling design #####

# because d_2002 includes data only for respondents (unit response), we need to duplicate rows for non-respondents
# so that the final dataset represents the sampling process
rows_to_add <- d_2002 %>%
  group_by( sampling_strata_region ) %>%
  summarise( to_add = unique( sample_size ) - n(),
             no.of.population = unique( no.of.population ),
             sample_size = unique( sample_size ),
             design_weight = unique( design_weight ) )

rows_to_add$to_add <- round( rows_to_add$to_add )

sum( rows_to_add$to_add ) # 18,885 non-respondents

replicated_rows <- rows_to_add[ rep( row.names( rows_to_add ), rows_to_add$to_add ), c( 1, 3:5 ) ]

d_2002_complete <- bind_rows( d_2002, replicated_rows ) # 50,067 individuals in the original sample

d_2002_complete <- d_2002_complete[ , c( 1, 15:17, 30:50 ) ]
summary( d_2002_complete )

# check death events
load('/Volumes/projects/LGBT Project data/Swedish Registers/dates_all.RData')

dates_all %>%
  filter( lopnr %in% d_2002_complete$lopnr,
          event_type == "death" ) %>%
  mutate( year = lubridate::year( date ) ) %>%
  count( year, name = "n_deaths" ) %>%
  mutate( year = as.character( year ) ) %>%
  bind_rows( summarise( ., year = "Total", n_deaths = sum( n_deaths ) ) ) # no death events in 2002
```

### 3. Mental Health Outcomes
#### 3.1. Self-reported
```{r}
# recent psychological distress
table( d_2002_complete$F2GHQ12, useNA = "always" )
d_2002_complete$psychological_distress <- factor( ifelse( d_2002_complete$F2GHQ12 >= 3, "Yes", "No" ),
                                                  levels = c( "Yes", "No" ) ) # psychological distress defined as a score >= 3
table( d_2002_complete$psychological_distress, useNA = "always" )

# suicidal thoughts
table( d_2002_complete$F2F45, useNA = "always" )
d_2002_complete$F2F45[ d_2002_complete$F2F45 == 9 ] <- NA
d_2002_complete$suicidal_thoughts <- factor( 
  case_when(
    d_2002_complete$F2F45 == 1 ~ "No",
    d_2002_complete$F2F45 %in% c( 2, 3, 4 ) ~ "Yes" ),
  levels = c( "Yes", "No" ) )
table( d_2002_complete$suicidal_thoughts, useNA = "always" )

# suicide attempts
table( d_2002_complete$F2F46, useNA = "always" )
d_2002_complete$F2F46[ d_2002_complete$F2F46 == 9 ] <- NA
d_2002_complete$suicide_attempts <- factor( 
  case_when(
    d_2002_complete$F2F46 == 1 ~ "No",
    d_2002_complete$F2F46 %in% c( 2, 3, 4 ) ~ "Yes" ),
  levels = c( "Yes", "No" ) )
table( d_2002_complete$suicide_attempts, useNA = "always" )
```

### 4. Complete-Case Analysis
```{r}
variables_list <- list(
  list( variable = "psychological_distress", condition = "Yes", name = "psychological_distress" ),
  list( variable = "suicidal_thoughts", condition = "Yes", name = "suicidal_thoughts" ),
  list( variable = "suicide_attempts", condition = "Yes", name = "suicide_attempts" ) )


########## Prevalence ##########

# create survey design
survey_design_cc <- svydesign( ids = ~ 1, 
                               strata = ~ sampling_strata_region,
                               weights = ~ design_weight,
                               fpc = ~ no.of.population,
                               data = d_2002_complete )

# overall prevalence
overall_list <- cal_prev_indi_overall_cc( variables_list = variables_list,
                                          design = subset( survey_design_cc, age <= 29 ),
                                          year = 2002 )

overall_prevalence_2002 <- Reduce( cbind, overall_list ) %>%
  mutate( sexual_identity = "Stockholm County" ) %>%
  relocate( sexual_identity )

writexl::write_xlsx( overall_prevalence_2002, "results_output/results_cc/overall_prevalence_2002_cc.xlsx" )

# overall prevalence by sex
results_list <- cal_prev_indi_cc( variables_list = variables_list, 
                                  design = subset( survey_design_cc, age <= 29 ), 
                                  year = 2002, 
                                  group_var = "sex" )

overall_prevalence_2002_by_sex <- Reduce( function( x, y ){
  merge( x, y, by = "sex" )
  }, 
  results_list ) %>%
  mutate( sexual_identity = "Stockholm County" ) %>%
  relocate( sexual_identity )

writexl::write_xlsx( overall_prevalence_2002_by_sex, "results_output/results_cc/overall_prevalence_2002_by_sex_cc.xlsx" )

# by sexual identity
results_list <- cal_prev_indi_cc( variables_list = variables_list, 
                                  design = subset( survey_design_cc, age <= 29 ), 
                                  year = 2002, 
                                  group_var = "sexual_identity_2010" )

prevalence_2002 <- Reduce( function( x, y ){
  merge( x, y, by = "sexual_identity_2010" )
  }, 
  results_list )

writexl::write_xlsx( prevalence_2002, "results_output/results_cc/prevalence_2002_by_identity_cc.xlsx" )

# by sex
results_list_by_sex <- cal_prev_indi_cc( variables_list = variables_list,
                                         design = subset( survey_design_cc, age <= 29 ),
                                         year = 2002,
                                         group_var = "sexual_identity_2010 + sex",
                                         subgroup = TRUE )

prevalence_2002_by_sex <- Reduce( function( x, y ){
  merge( x, y, by = c( "sexual_identity_2010", "sex" ) )
  },
  results_list_by_sex )

writexl::write_xlsx( prevalence_2002_by_sex, "results_output/results_cc/prevalence_2002_by_sex_cc.xlsx" )

# by generation
results_list_by_generation <- cal_prev_indi_cc( variables_list = variables_list,
                                                design = subset( survey_design_cc, age <= 29 ),
                                                year = 2002,
                                                group_var = "sexual_identity_2010 + generation",
                                                subgroup = TRUE )

prevalence_2002_by_generation <- Reduce( function( x, y ){
  merge( x, y, by = c( "sexual_identity_2010", "generation" ) )
  }, 
  results_list_by_generation )

writexl::write_xlsx( prevalence_2002_by_generation, "results_output/results_cc/prevalence_2002_by_generation_cc.xlsx" )


########## Prevalence Ratio ##########

str( d_2002_complete )

# create survey design
survey_design_cc <- svydesign( ids = ~ 1, 
                               strata = ~ sampling_strata_region,
                               weights = ~ design_weight,
                               fpc = ~ no.of.population,
                               data = d_2002_complete %>%
                                 mutate( psychological_distress = ifelse( psychological_distress == "Yes", 1, 0 ),
                                         suicidal_thoughts = ifelse( suicidal_thoughts == "Yes", 1, 0 ),
                                         suicide_attempts = ifelse( suicide_attempts == "Yes", 1, 0 ) ) )

# crude analysis (overall)
models_list_crude <- cal_pr_indi_cc( 
  design = subset( survey_design_cc, age <= 29 ), 
  exposure = "sexual_identity_2010", 
  outcome_list = variables_list,
  year = 2002 )

# adjusted analysis (overall)
models_list_adjusted <- cal_pr_indi_cc( 
  design = subset( survey_design_cc, age <= 29 ), 
  exposure = "sexual_identity_2010", 
  outcome_list = variables_list,
  covariates = "age + sex + country_of_birth",
  year = 2002 )

pr_crude_cc <- extract_pr_cc(
  model_list = models_list_crude,
  exposure_var = "sexual_identity_2010" ) %>%
  mutate( model_type = "crude" )

pr_adjusted_cc <- extract_pr_cc(
  model_list = models_list_adjusted,
  exposure_var = "sexual_identity_2010" ) %>%
  mutate( model_type = "adjusted" )

pr_2002_cc <- bind_rows( pr_crude_cc, pr_adjusted_cc )
writexl::write_xlsx( pr_2002_cc, "results_output/results_cc/pr_2002_cc.xlsx" )

# crude analysis (MALE)
levels( d_2002_complete$sex )

models_list_male_crude <- cal_pr_indi_cc( 
  design = subset( survey_design_cc, age <= 29 ), 
  exposure = "sexual_identity_2010 * sex", 
  outcome_list = variables_list,
  year = 2002 )

# adjusted analysis (MALE)
models_list_male_adjusted <- cal_pr_indi_cc( 
  design = subset( survey_design_cc, age <= 29 ), 
  exposure = "sexual_identity_2010 * sex", 
  outcome_list = variables_list,
  covariates = "age + country_of_birth",
  year = 2002 )

summary( models_list_male_crude[[ 1 ]] ) # random check
summary( models_list_male_adjusted[[ 1 ]] ) # random check

pr_male_crude_cc <- extract_pr_by_sex_cc(
  model_list = models_list_male_crude,
  exposure_var = "sexual_identity_2010" ) %>%
  mutate( model_type = "crude",
          sex = "Male" )

pr_male_adjusted_cc <- extract_pr_by_sex_cc(
  model_list = models_list_male_adjusted,
  exposure_var = "sexual_identity_2010" ) %>%
  mutate( model_type = "adjusted",
          sex = "Male" )

pr_male_2002_cc <- bind_rows( pr_male_crude_cc, pr_male_adjusted_cc )
writexl::write_xlsx( pr_male_2002_cc, "results_output/results_cc/pr_male_2002_cc.xlsx" )


# create survey design
survey_design_cc <- svydesign( ids = ~ 1, 
                               strata = ~ sampling_strata_region,
                               weights = ~ design_weight,
                               fpc = ~ no.of.population,
                               data = d_2002_complete %>%
                                 mutate( sex = factor( sex, levels = c( "Female", "Male" ) ),
                                         psychological_distress = ifelse( psychological_distress == "Yes", 1, 0 ),
                                         suicidal_thoughts = ifelse( suicidal_thoughts == "Yes", 1, 0 ),
                                         suicide_attempts = ifelse( suicide_attempts == "Yes", 1, 0 ) ) )

# crude analysis (FEMALE)
models_list_female_crude <- cal_pr_indi_cc( 
  design = subset( survey_design_cc, age <= 29 ), 
  exposure = "sexual_identity_2010 * sex", 
  outcome_list = variables_list,
  year = 2002 )

# adjusted analysis (FEMALE)
models_list_female_adjusted <- cal_pr_indi_cc( 
  design = subset( survey_design_cc, age <= 29 ), 
  exposure = "sexual_identity_2010 * sex", 
  outcome_list = variables_list,
  covariates = "age + country_of_birth",
  year = 2002 )

summary( models_list_female_crude[[ 1 ]] ) # random check
summary( models_list_female_adjusted[[ 1 ]] )

pr_female_crude_cc <- extract_pr_by_sex_cc(
  model_list = models_list_female_crude,
  exposure_var = "sexual_identity_2010" ) %>%
  mutate( model_type = "crude",
          sex = "Female" )

pr_female_adjusted_cc <- extract_pr_by_sex_cc(
  model_list = models_list_female_adjusted,
  exposure_var = "sexual_identity_2010" ) %>%
  mutate( model_type = "adjusted",
          sex = "Female" )

pr_female_2002_cc <- bind_rows( pr_female_crude_cc, pr_female_adjusted_cc )
writexl::write_xlsx( pr_female_2002_cc, "results_output/results_cc/pr_female_2002_cc.xlsx" )


########## Prevalence Difference ##########

str( d_2002_complete )

# create survey design
survey_design_cc <- svydesign( ids = ~ 1, 
                               strata = ~ sampling_strata_region,
                               weights = ~ design_weight,
                               fpc = ~ no.of.population,
                               data = d_2002_complete %>%
                                 mutate( psychological_distress = ifelse( psychological_distress == "Yes", 1, 0 ),
                                         suicidal_thoughts = ifelse( suicidal_thoughts == "Yes", 1, 0 ),
                                         suicide_attempts = ifelse( suicide_attempts == "Yes", 1, 0 ) ) )

# crude analysis
models_list_crude <- cal_pd_indi_cc( 
  design = subset( survey_design_cc, age <= 29 ), 
  exposure = "sexual_identity_2010", 
  outcome_list = variables_list,
  year = 2002 )

# adjusted analysis
models_list_adjusted <- cal_pd_indi_cc( 
  design = subset( survey_design_cc, age <= 29 ), 
  exposure = "sexual_identity_2010", 
  outcome_list = variables_list,
  covariates = "age + sex + country_of_birth",
  year = 2002 )

pd_crude_cc <- extract_pd_cc(
  model_list = models_list_crude,
  exposure_var = "sexual_identity_2010" ) %>%
  mutate( model_type = "crude" )

pd_adjusted_cc <- extract_pd_cc(
  model_list = models_list_adjusted,
  exposure_var = "sexual_identity_2010" ) %>%
  mutate( model_type = "adjusted" )

pd_2002_cc <- bind_rows( pd_crude_cc, pd_adjusted_cc )
writexl::write_xlsx( pd_2002_cc, "results_output/results_cc/pd_2002_cc.xlsx" )

# crude analysis (MALE)
levels( d_2002_complete$sex )

models_list_male_crude <- cal_pd_indi_cc( 
  design = subset( survey_design_cc, age <= 29 ), 
  exposure = "sexual_identity_2010 * sex", 
  outcome_list = variables_list,
  year = 2002 )

# adjusted analysis (MALE)
models_list_male_adjusted <- cal_pd_indi_cc( 
  design = subset( survey_design_cc, age <= 29 ), 
  exposure = "sexual_identity_2010 * sex", 
  outcome_list = variables_list,
  covariates = "age + country_of_birth",
  year = 2002 )

summary( models_list_male_crude[[ 1 ]] ) # random check
summary( models_list_male_adjusted[[ 1 ]] ) # random check

pd_male_crude_cc <- extract_pd_by_sex_cc(
  model_list = models_list_male_crude,
  exposure_var = "sexual_identity_2010" ) %>%
  mutate( model_type = "crude",
          sex = "Male" )

pd_male_adjusted_cc <- extract_pd_by_sex_cc(
  model_list = models_list_male_adjusted,
  exposure_var = "sexual_identity_2010" ) %>%
  mutate( model_type = "adjusted",
          sex = "Male" )

pd_male_2002_cc <- bind_rows( pd_male_crude_cc, pd_male_adjusted_cc )
writexl::write_xlsx( pd_male_2002_cc, "results_output/results_cc/pd_male_2002_cc.xlsx" )


# create survey design
survey_design_cc <- svydesign( ids = ~ 1, 
                               strata = ~ sampling_strata_region,
                               weights = ~ design_weight,
                               fpc = ~ no.of.population,
                               data = d_2002_complete %>%
                                 mutate( sex = factor( sex, levels = c( "Female", "Male" ) ),
                                         psychological_distress = ifelse( psychological_distress == "Yes", 1, 0 ),
                                         suicidal_thoughts = ifelse( suicidal_thoughts == "Yes", 1, 0 ),
                                         suicide_attempts = ifelse( suicide_attempts == "Yes", 1, 0 ) ) )

# crude analysis (FEMALE)
models_list_female_crude <- cal_pd_indi_cc( 
  design = subset( survey_design_cc, age <= 29 ), 
  exposure = "sexual_identity_2010 * sex", 
  outcome_list = variables_list,
  year = 2002 )

# adjusted analysis (FEMALE)
models_list_female_adjusted <- cal_pd_indi_cc( 
  design = subset( survey_design_cc, age <= 29 ), 
  exposure = "sexual_identity_2010 * sex", 
  outcome_list = variables_list,
  covariates = "age + country_of_birth",
  year = 2002 )

summary( models_list_female_crude[[ 1 ]] ) # random check
summary( models_list_female_adjusted[[ 1 ]] )

pd_female_crude_cc <- extract_pd_by_sex_cc(
  model_list = models_list_female_crude,
  exposure_var = "sexual_identity_2010" ) %>%
  mutate( model_type = "crude",
          sex = "Female" )

pd_female_adjusted_cc <- extract_pd_by_sex_cc(
  model_list = models_list_female_adjusted,
  exposure_var = "sexual_identity_2010" ) %>%
  mutate( model_type = "adjusted",
          sex = "Female" )

pd_female_2002_cc <- bind_rows( pd_female_crude_cc, pd_female_adjusted_cc )
writexl::write_xlsx( pd_female_2002_cc, "results_output/results_cc/pd_female_2002_cc.xlsx" )
```